-- DATEDIFF로 마지막날-시작날 차이를 구하고(기간이기때문에 +1)
-- AVG로 평균값을 구함
-- ROUND로 소수점 몇 번째 까지 출력할지 설정

SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC