-- 의 회원 ID, 닉네임, 총거래금
SELECT UGU.USER_ID, UGU.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_USER UGU
ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS LIKE 'DONE'
GROUP BY UGU.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC